### ISSUE TITLE
[error]A supported task execution handler was not found.

### ISSUE THREAD

**Issue by mohammedmax** [hey24sheep/azure-flutter-tasks#100]
Does the extension work with tfs 2018 release?

[error]A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details.

**Comment by hey24sheep** [comment]
Hi, this extension was made for only for Azure pipelines. I have never been asked or tried to test this extension on TFS. 

It's out of scope for this extension but you can test on your own.
