### ISSUE TITLE
Build target: mobile - expected result

### ISSUE THREAD

**Issue by ktnishide** [hey24sheep/azure-flutter-tasks#105]
Hi,

what is the expected result for a build using target: mobile? 
I wanted to have .ipa and .aab but it is not creating .ipa

it creates .app, .apk and .aab

Is there a way to achieve it with a single task? 

thanks!

**Comment by hey24sheep** [comment]
You can't generate it in a single task, for IOS a different build is needed. You can go through the WIKI page here and also check [StackOverflow](https://stackoverflow.com/questions/55332303/how-can-i-generate-ipa-file-in-flutter-in-android-studio). Go through the closed issues as well, you might find some help. 

For IOS build, you will have to select the IOS build as well.
