### ISSUE TITLE
Your bundleArchive in line 88 does not handle spaces

### ISSUE THREAD

**Issue by sk92129** [hey24sheep/azure-flutter-tasks#106]
https://github.com/hey24sheep/azure-flutter-tasks/blob/master/tasks/install/index.js
Line 88 does not handle spaces in the path.
The next line to extract the zip will fail because the path did not escape any special characters like spaces.

**Comment by sk92129** [comment]
##[debug]Agent running environment resource - Disk:D:\ Data available:47084.00MB out of 307196.00MB, Memory: used 17MB out of 8191MB, CPU: usage 17.10
##[debug]download complete
##[debug]Succeeded to download 'D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\a557b362-8fee-44a6-bf2b-2f7950c15cda' archive from 'https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.16.3-stable.zip'
##[debug]Extracting 'https://storage.googleapis.com/flutter_infra_release/releases/stable/windows/flutter_windows_3.16.3-stable.zip' archive
Extracting archive
##[debug]Agent.Version=3.232.1
##[debug]Agent.TempDirectory=D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp
##[debug]testing directory 'D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\75e53c74-2ab8-43f2-930d-416c6f6924b0'
##[debug]testing directory 'D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp'
##[debug]mkdir 'D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\75e53c74-2ab8-43f2-930d-416c6f6924b0'
##[debug]which 'C:\Windows\system32\chcp.com'
##[debug]found: 'C:\Windows\system32\chcp.com'
##[debug]C:\Windows\system32\chcp.com arg: 65001
##[debug]C:\Windows\system32\chcp.com arg: 65001
##[debug]exec tool: C:\Windows\system32\chcp.com
##[debug]exec tool: C:\Windows\system32\chcp.com
##[debug]arguments:
##[debug]arguments:
##[debug]   65001
##[debug]   65001
C:\Windows\system32\chcp.com 65001
Active code page: 65001
##[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
##[debug]Exit code 0 received from tool 'C:\Windows\system32\chcp.com'
##[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
##[debug]STDIO streams have closed for tool 'C:\Windows\system32\chcp.com'
##[debug]which 'powershell'
##[debug]found: 'C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe'
##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command
##[debug]C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe arg: $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\a557b362-8fee-44a6-bf2b-2f7950c15cda', 'D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\75e53c74-2ab8-43f2-930d-416c6f6924b0')
##[debug]exec tool: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
##[debug]arguments:
##[debug]   -NoLogo
##[debug]   -Sta
##[debug]   -NoProfile
##[debug]   -NonInteractive
##[debug]   -ExecutionPolicy
##[debug]   Unrestricted
##[debug]   -Command
##[debug]   $ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\a557b362-8fee-44a6-bf2b-2f7950c15cda', 'D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\75e53c74-2ab8-43f2-930d-416c6f6924b0')
C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -NoLogo -Sta -NoProfile -NonInteractive -ExecutionPolicy Unrestricted -Command "$ErrorActionPreference = 'Stop' ; try { Add-Type -AssemblyName System.IO.Compression.FileSystem } catch { } ; [System.IO.Compression.ZipFile]::ExtractToDirectory('D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\a557b362-8fee-44a6-bf2b-2f7950c15cda', 'D:\Build Agents\SomeServerName Mobile Agent 04\_work\_temp\75e53c74-2ab8-43f2-930d-416c6f6924b0')"
##[debug]Agent running environment resource - Disk:D:\ Data available:46640.00MB out of 307196.00MB, Memory: used 17MB out of 8191MB, CPU: usage 13.85
##[debug]Agent running environment resource - Disk:D:\ Data available:46301.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 11.69
##[debug]Agent running environment resource - Disk:D:\ Data available:45873.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 10.09
##[debug]Agent running environment resource - Disk:D:\ Data available:45496.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 8.87
##[debug]Agent running environment resource - Disk:D:\ Data available:45243.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 7.91
##[debug]Agent running environment resource - Disk:D:\ Data available:44971.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 7.14
##[debug]Agent running environment resource - Disk:D:\ Data available:44675.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 6.50
##[debug]Agent running environment resource - Disk:D:\ Data available:44540.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 5.97
##[debug]Agent running environment resource - Disk:D:\ Data available:44513.00MB out of 307196.00MB, Memory: used 32MB out of 8191MB, CPU: usage 5.55
Exception calling "ExtractToDirectory" with "2" argument(s): "Could not find a part of the path 'D:\Build

**Comment by hey24sheep** [comment]
This issue will only happen on local hosted agents that too in environments where spaces are being used. I don't think this can easily be fixed as "Spaces" are not used on cloud instances (generally). I will say, you can rename your file/folder names to fix it.
