### ISSUE TITLE
TypeError on build 'Cannot read property 'split' of null'

### ISSUE THREAD

**Issue by martipello** [hey24sheep/azure-flutter-tasks#11]
Getting an error immediately when building : 
    
    TypeError: Cannot read property 'split' of null 

using this task :

    - task: FlutterBuild@0
      name: 'build_dev'
      inputs:
        target: 'apk'
        entryPoint: 'lib/main_dev.dart'
        projectDirectory: '$(System.DefaultWorkingDirectory)/apps/MyApp/'
        flutterDirectory: './flutter'
        verboseMode: true
        buildFlavour: 'dev'
        buildName: '0.0.1'
        buildNumber: ''
        dartDefine: 'TIMESHEET_BOX_KEY=$(secret_key) --dart-define FILE_BOX_KEY=$(secret_key)'
        extraArgs: '--release'
            
on azure : 
    
    pool:
        vmImage: 'macOS-10.15'

Locally i can run :
    
    flutter build apk -t lib/main_dev.dart --flavor dev --release

on my machine :
    
    Flutter (Channel stable, 2.5.1, on macOS 11.2.3 20D91 darwin-arm, locale en-GB)

and it works fine

**Comment by martipello** [comment]
Just noticed this actually failed all my builds iOS and Android

**Comment by hey24sheep** [comment]
Oh sorry, I forgot to put null check :( I will fix it asap.

**Comment by hey24sheep** [comment]
I pushed a fix and published the extension. Let me know if it is fixed by closing this issue.

**Comment by martipello** [comment]
> I pushed a fix and published the extension (it will take 5minutes to update). Let me know if it is fixed by closing this issue.

will do many thanks

**Comment by hey24sheep** [comment]
Hi, Closing this issue as I have tested this on our prod environment and it is now fixed and working. If you still face any problems, create a new issue and I will be happy to help.

**Comment by martipello** [comment]
So sorry I forgot to close it did work thanks for the super quick fix
