### ISSUE TITLE
Flutter Test has no option for custom flutter install path

### ISSUE THREAD

**Issue by cliffAtOsaic** [hey24sheep/azure-flutter-tasks#110]
Flutter Build task has an option called "Path to the Flutter SDK" where I can input a custom SDK install path.

Flutter Test task, however, is lacking this option.

How do I tell Flutter Test task where to find the Flutter SDK?

**Comment by hey24sheep** [comment]
@cliffAtOsaic Please go through the [readme guide](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/README.md#env), there is an "Env" task which is there for this purpose only, to set environment variables for Flutter. That way, you will be to give it custom path.

Make sure to run your "env" task before your "test" task, I hope this helps.

**Comment by cliffAtOsaic** [comment]
That is working for me, thank you.  When I removed "Flutter Install" I saw the property under Build but not under Test.  But since Env is working, that becomes irrelevant.  :)
