### ISSUE TITLE
Version number is not getting updated

### ISSUE THREAD

**Issue by KrishnaChaitanyaVedantam** [hey24sheep/azure-flutter-tasks#114]
In the Build task, when I provide buildName as 2.0.3 and buildNumber as 85, the ipa is getting generated with v1.0.0(85) instead v2.0.3(85)

**Comment by hey24sheep** [comment]
That's cuz you haven't configured your application in the correct way. Refer to Flutter's doc or this [Stackoverflow](https://stackoverflow.com/questions/54357468/how-to-set-build-and-version-number-of-flutter-app)

**Comment by KrishnaChaitanyaVedantam** [comment]
Hi @hey24sheep 

Thanks for your reply. I tried in both ways. 

This is what I declared in pubspec.yaml
version: 2.0.3+85

In this case also I'm getting v1.0.0(85) from the iPA.

And, I tried to pass the buildName and buildNumber directly in the FlutterBuild Task like below. But still getting the same version v1.0.0(85)

      - task: FlutterBuild@0
        displayName: "Build IOS"
        inputs:
          target: ios
          projectDirectory: "my_app"
          buildName: '2.0.3'
          buildNumber: '85'
          iosCodesign: false
          extraArgs: '--release --dart-define=ENVIRONMENT=QA --build-name=myapp-qa'
          buildFlavour: 'qa'

**Comment by hey24sheep** [comment]
Have you set the variables correctly in your IOS configuration plist file?

**Comment by KrishnaChaitanyaVedantam** [comment]
Hi,

I tried even by changing the info.plist values as well. But still it is having the same issue.

Regards,
Chaitanya

**Comment by hey24sheep** [comment]
Can you post your ".plist" file here, hide your keys or any other special values. It's a configuration issue from your side. I can't help you much here. I would recommend you ask this on Stackoverflow and maybe someone can help you there.
