### ISSUE TITLE
How to trigger a azure build failure on Pub Get advisory alerts

### ISSUE THREAD

**Issue by sk92129** [hey24sheep/azure-flutter-tasks#117]
I saw in the Google pub dev security web pages, that the "flutter pub get" will generate a message like below when a dependency contains a security or alert advisory.

https://dart.dev/tools/pub/security-advisories

$ dart pub get
Resolving dependencies...
http 0.13.0 (affected by advisory: [^0], 1.2.0 available)
Got dependencies!
Dependencies are affected by security advisories:
  [^0]: https://github.com/advisories/GHSA-4rgh-jx4f-qfcq

When the Flutter Tasks runs in my azure pipeline and I explicitly either do a pub get, or a build, I see all the dependencies fetched.

How do I add a way to alert me when an advisory is displayed in the output?

**Comment by hey24sheep** [comment]
There is no way to do that in this extension and can't be a part of it. I would recommend you to create a powershell script that you can run the dart pub get and read the stdout and then do whatever needs to be done

**Comment by hey24sheep** [comment]
I am closing this issue as out of scope and infeasible
