### ISSUE TITLE
Update iOS SDK to 17

### ISSUE THREAD

**Issue by zigapovhe** [hey24sheep/azure-flutter-tasks#118]
Hi @hey24sheep !
When I build my Flutter app using your pipeline tasks, it works, but I have started receiving emails from Apple that look like this:

> Hello,
> 
> We noticed one or more issues with a recent delivery for the following app:
> 
> my_app_name
> Version 2.8.3
> Build 180
> Although delivery was successful, you may want to correct the following issues in your next delivery. Once you've corrected the issues, upload a new binary to App Store Connect.
> 
> ITMS-90725: SDK version issue - This app was built with the iOS 16.2 SDK. Starting April 29, 2024, all iOS and iPadOS apps must be built with the iOS 17 SDK or later, included in Xcode 15 or later, in order to be uploaded to App Store Connect or submitted for distribution.
> 
> Apple Developer Relations

Looks like a plugin the pipeline is using for building iOS apps needs to be updated?

**Comment by hey24sheep** [comment]
Hi, this extension is just an interface to use the CLI on Pipelines. Whatever IOS SDK is supplied with Flutter is used so, I'll recommend you to open an issue on Flutter's GitHub for this. 

As this issue is related to Flutter and not this, I'm closing it.

Thanks
