### ISSUE TITLE
Error with 0.4.0 FlutterInstall Task on macos-14

### ISSUE THREAD

**Issue by tghamm** [hey24sheep/azure-flutter-tasks#126]
Same build worked yesterday, it looks like an update to the task is causing a failure during the flutter install step on macos-14 in Azure DevOps:
```bash
Starting: FlutterInstall
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.4.0
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io/)
==============================================================================
##[error]The current operating system is not capable of running this task. That typically means the task was written for Windows only. For example, written for Windows Desktop PowerShell.
Finishing: FlutterInstall
```

**Comment by hey24sheep** [comment]
https://github.com/hey24sheep/azure-flutter-tasks/issues/124

**Comment by hey24sheep** [comment]
Released new version **0.4.1**. Can you validate once, thanks

**Comment by eljorgit** [comment]
Hi @hey24sheep, this seems to fail again as I get this error:

`
Starting: FlutterInstall
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.4.1
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io/)
==============================================================================
##[error]StatusCodeError: 404 - "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: flutter_infra_release/releases/releases_undefined.json</Details></Error>"
Finishing: FlutterInstall
`

**Comment by tghamm** [comment]
Different error now:
```bash
##[error]StatusCodeError: 404 - "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: flutter_infra_release/releases/releases_undefined.json</Details></Error>"
```

**Comment by eljorgit** [comment]
Now this error:

`Starting: FlutterInstall
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.4.1
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io/)
==============================================================================
##[error]StatusCodeError: 404 - "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: flutter_infra_release/releases/releases_undefined.json</Details></Error>"
Finishing: FlutterInstall`

**Comment by hey24sheep** [comment]
I see, the issue is with `os.platform()` in "install task"

**Comment by tghamm** [comment]
Appreciate you jumping on this so quickly :)

**Comment by hey24sheep** [comment]
They changed something internally. I am pushing a check first to find the platform. You will need to give me the initial log saying `[INFO] Found architecture xxxxxx`. Then only I will be able to push another version which will fix it.

**Comment by hey24sheep** [comment]
New version 0.4.2 will be available in about 6-7 minutes, please re-run after that and give me the arch type name there. I will then push a fix after that

**Comment by eljorgit** [comment]
Hi @hey24sheep this also happens to me in Ubuntu Server 22.04.3 LTS

**Comment by hey24sheep** [comment]
@eljorgit so the code that is failing is this 

```
function findArchitecture() {
	if (os.platform() === 'darwin')
		return "macos";
	else if (os.platform() === 'linux')
		return "linux";
	return "windows";
}
```

Which gives "arch" type for the url
`https://storage.googleapis.com/flutter_infra_release/releases/releases_${arch}.json`
The error shows "undefined" as the URL

**Comment by hey24sheep** [comment]
So paste your VM platform names here. I will check. Azure has messed it up. I have just updated the Node to 20 to fix #124

**Comment by eljorgit** [comment]
You mean this?
(run `hostnamectl`)
```
Static hostname: xxxxxx
       Icon name: computer-container
         Chassis: container
      Machine ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
         Boot ID: xxxxxxxxxxxxxxxxxxxxxxxxxx
  Virtualization: lxc
Operating System: Ubuntu 22.04.3 LTS              
          Kernel: Linux 6.2.16-3-pve
    Architecture: x86-64
```

**Comment by eljorgit** [comment]
On the pipeline task I get this:

```
Starting: FlutterInstall
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.4.2
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io/)
==============================================================================
[INFO] Found architecture  linux
##[error]StatusCodeError: 404 - "<?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: flutter_infra_release/releases/releases_undefined.json</Details></Error>"
Finishing: FlutterInstall
```

I think there is an extra white space just before linux, dont know if could be this

**Comment by hey24sheep** [comment]
@eljorgit @tghamm Please check, it should be working now. New version **0.4.3**

**Comment by eljorgit** [comment]
It is working for me, thanks for this very quick fix ❤️

**Comment by hey24sheep** [comment]
@eljorgit Great, thanks for confirming

**Comment by tghamm** [comment]
Running now on a mac agent, will report shortly :)

**Comment by tghamm** [comment]
@hey24sheep everything seems to be working now! Thanks for the quick fix!

**Comment by hey24sheep** [comment]
Nice, thanks for confirming
