### ISSUE TITLE
Azure DevOps InstallAppleCertificate Fails with OpenSSL Flag -legacy on macOS Agent

### ISSUE THREAD

**Issue by jaimisdomadiya** [hey24sheep/azure-flutter-tasks#130]
The InstallAppleCertificate task in Azure DevOps is failing on macOS agents when attempting to parse a valid .p12 certificate. The failure occurs during the OpenSSL command execution with the following error:

`pkcs12: Unrecognized flag nodes -legacy
pkcs12: Use -help for summary.
unable to load certificate
140704446801536:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
`

Steps to Reproduce
Set up an Azure DevOps pipeline using the InstallAppleCertificate task.
Use a valid .p12 certificate file (tested locally and verified to be working).
Add the opensslPkcsArgs: '-legacy' argument to the task to ensure compatibility with legacy certificates.
Run the pipeline on a macOS agent (macOS-15 or macOS-14).

Expected Behavior
The .p12 certificate should be parsed successfully, and the certificate should install without errors.

Actual Behavior
The task fails with the error:
`pkcs12: Unrecognized flag nodes -legacy
unable to load certificate
140704446801536:error:0909006C:PEM routines:get_name:no start line:crypto/pem/pem_lib.c:745:Expecting: TRUSTED CERTIFICATE
`

Environment Details
Azure DevOps Pipeline Agent: macOS-15
OpenSSL Version: [Include version after debugging step]
Task Version: InstallAppleCertificate v2.246.5
Certificate: .p12 file verified to be valid locally.

**Comment by hey24sheep** [comment]
I don't think that it's related to this extension. You can raise this issue on their repository, thanks. Feel free to reopen if in case I misinterpreted and this issue is related to my extension.
