### ISSUE TITLE
Multiple --dart-define variables doesn't work

### ISSUE THREAD

**Issue by aignerjo** [hey24sheep/azure-flutter-tasks#14]
Using multiple --dart-define variables does not work at the moment. One variable works just fine but whenever adding more than one results in having none set at all. 

The documentation of yours suggests adding the dart defines in a format like this:

`FIRST_ENV_VARIABLE=whatever --dart-define=SECOND_ENV_VARIABLE=whatever `

**Comment by hey24sheep** [comment]
It should be used like this `--no-tree-shake-icons --dart-define=VAR1=value --dart-define=VAR2=value2`.

How are you defining your arguments?

**Comment by aignerjo** [comment]
As it is stated in the Readme: 

(Optional). Set dartDefine compile-time variables. Example: "Some_Var=Some_val --dart-define=Some_Var2=Val"

I'ts quite confusing: dartDefine should always be prefixed with `--dart-define` and I guess it should not have anything to do with `--no-tree-shake-icons`

We've tried multiple versions:
`--dart-define=A=valueA --dart-define=B=valueB`
`A=valueA --dart-define=B=valueB`

**Comment by hey24sheep** [comment]
Sorry, I wasn't detailed. I mean't to say you could try the command in "extra-args" instead of "dart-define" and check if that works. I just wrote tree-shake for reference, just ignore that part.

I think looking at the [code](https://github.com/hey24sheep/azure-flutter-tasks/blob/968b2023fa724812f677beda1eb92e59c992d645/tasks/build/index.ts#L180) I feel I have to change the way input is taken.

**Comment by aignerjo** [comment]
We've tried extra-args and faced the same issue. Is it an issue with quoting the arguments or something?

**Comment by hey24sheep** [comment]
Could you try [this](https://medium.com/@tatsu.ukraine/flutter-2-2-dart-defines-and-breaking-changes-here-we-go-again-ce40cfea74fd) and check if your project is setup properly and let me know if it works? 

If it works, that means the way dart-define is right now it is working fine. Because if I change it in any way it will be a breaking change for all current working pipelines.

**Comment by aignerjo** [comment]
Already done (at least for the android part) - We've added log statements in the build.gradle to see if the environment variables are set correctly. But whenever we use more than one dart-define we see **null**

**Comment by hey24sheep** [comment]
Does it work locally? Also, if you put this `--dart-define=A=valueA --dart-define=B=valueB` in `extraArgs` does that make the same result?

**Comment by aignerjo** [comment]
Yeah locally it works just fine. extraArgs does not change the output.

**Comment by aignerjo** [comment]
Can you validate that multiple arguments are working for you?

**Comment by hey24sheep** [comment]
I am out of ideas. Even if I change the way "Dart Define Input" is taken `VAR=value --dart-define=VAR2=value2` to `var=value var2=value` that won't fix anything as `extraArgs` is producing the same output. You could read [this](https://github.com/flutter/flutter/issues/55870). 

We do not use "--dart-define" in our app so I cannot test it :(

**Comment by aignerjo** [comment]
With [this](https://github.com/aloisdeniel/vsts-flutter-tasks/issues/80#issuecomment-813819629) workaround it's actually working. Did not dig deeper into the issue with the plugin.

**Comment by jtmuller5** [comment]
@hey24sheep I tried what you suggested in your last comment and it still doesn't seem to work. 

For now, I'm going to handle the bundle ID and display name in native flavors and pass in a single environment variable to my dart-define.

**Comment by hey24sheep** [comment]
@jtmuller5 Good catch, I actually missed the fix for IOS and AAB.

**Comment by hey24sheep** [comment]
@jtmuller5 I have fixed the exiting one for other platforms and created a new `dartDefineMulti` argument to not break any existing pipelines. It can be used as `key1=val1 foo=bar key2=val2`. 

In case of Desktop platforms, `extraArgs` can be used as `--dart-define=foo=bar --dart-define=bar=zoo`

I am closing this issue in response to commit 8a3d365. Feel free to create a new issue if you face any issues.
