### ISSUE TITLE
Build task error "No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi" since Flutter 2.5.2

### ISSUE THREAD

**Issue by xmashallax** [hey24sheep/azure-flutter-tasks#16]
Hey,

the issue is not directly related to your extension as it seems to be a Google/Android/Flutter problem. But I didn't know where to ask since my problem specifically involve Azure DevOps and your tasks. If it's too far away in your opinion feel free to close.

Today I upgraded to Flutter 2.5.2 and the most recent Android SDK and then a new build error occured:

No toolchains found in the NDK toolchains folder for ABI with prefix: arm-linux-androideabi

![image](https://user-images.githubusercontent.com/64989292/136294010-f504d7ee-06d7-43c2-8fba-51305371421e.png)

A working fix for my local build was to downgrade the NDK via the SDK Manager in Android Studio. The solution is mentioned in several issues around the internet
https://stackoverflow.com/questions/66922162/no-toolchains-found-in-the-ndk-toolchains-folder-for-abi-with-prefix-arm-linux

Using the version 22.0 instead of 23.0 fixes my local build.

![image](https://user-images.githubusercontent.com/64989292/136294206-f16a91ce-4bb1-413b-995f-32a026f27bf5.png)

But the same problem occurs when building in Azure DevOps. And here I am struggling to apply my fix. According to the [docs](https://github.com/actions/virtual-environments/blob/main/images/win/Windows2019-Readme.md) there are 3 versions of NDK installed.

![image](https://user-images.githubusercontent.com/64989292/136294484-4c2444b0-e04e-41dc-b21f-e51a08cea9d5.png)

I don't know how to uninstall NDK in the virtual machine. Has anyone already seen (and fixed) this problem?

Thanks for any support!

**Comment by hey24sheep** [comment]
Hi, that's a new error. Unfortunately Azure DevOps doesn't have any documentation regarding uninstall/install of predefined stuff.

But here is a [solution](https://stackoverflow.com/questions/60404457/no-version-of-ndk-matched-the-requested-version) which could work, you could give it a try.

**Comment by xmashallax** [comment]
Hi, thanks for the reply.

Your hint was correct. I solved the problem by inserting a specific ndk version (21.4.7075529) into the build.gradle file. This version is also installed on the build VM, so the Flutter build task succeeds now.

[https://stackoverflow.com/a/65698078](https://stackoverflow.com/a/65698078)
