### ISSUE TITLE
How to install on custom buildserver

### ISSUE THREAD

**Issue by JardarM** [hey24sheep/azure-flutter-tasks#25]
Hi,

I am running a linux build server. 

Is there a way to have this installed on the my server?

**Comment by hey24sheep** [comment]
Hi, @JardarM are you running a VS Agent on a local machine? or are you running your own custom Linux build server?

If it's the former, just go to [Azure Marketplace](https://marketplace.visualstudio.com/items?itemName=Hey24sheep.flutter) and install it on your Azure DevOps directory.

If it's the later, you can't use this library as it is only for Azure DevOps. You could read through the code and create your own scripts based on the code.

I am closing this issue. Let me know if you have anymore questions.
