### ISSUE TITLE
Stopped working since the update from 0.2.43 to 0.3.0

### ISSUE THREAD

**Issue by RivkaAltshuler** [hey24sheep/azure-flutter-tasks#27]
Since the update from 0.2.43 to 0.3.0 we tasks fail with the following message:
A supported task execution handler was not found. This error usually means the task does not carry an implementation that is compatible with your current operating system. Contact the task author for more details

Environment:
Microsoft Visual Studio Team Foundation Server Version 16.131.27701.1
Microsoft Windows [Version 6.3.9600]

**Comment by hey24sheep** [comment]
Are you running a local build agent? 

You have to download the latest build agent from [here](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.188.3).

If you read the Changelog, you will know what has changed and why. All hosted agents are working on my build server as they automatically use Node10.

If updating your build agent doesn't fix your problem or you don't want to update it. You can download the .vsix of the previous version and manually install it on your Azure.

**Comment by hey24sheep** [comment]
Here is the [file](https://github.com/microsoft/azure-pipelines-agent/releases/tag/v2.188.3) download the vsix and install it on your Azure.

**Comment by RivkaAltshuler** [comment]
It does not navigate me to the vsix

**Comment by hey24sheep** [comment]
I'm sorry, I gave the wrong link. Release are found [here](https://github.com/hey24sheep/azure-flutter-tasks/releases).

Here is the extension 0.2.63 direct download of [vsix file](https://github.com/hey24sheep/azure-flutter-tasks/releases/download/node6_0.2.63/hey24sheep.flutter-0.2.63.vsix).

I will recommend you to update your build agents as in future they will be deperecated and this extension updates will be invalid for you as well.

**Comment by RivkaAltshuler** [comment]
I created a publisher to upload the VSIX, but it is blocked, only you can upload it...
If I will do that, I need to create a new VSIX with another publisher

**Comment by hey24sheep** [comment]
You don't need to upload to publisher portal. You have to install it, [read this](https://docs.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser).

**Comment by hey24sheep** [comment]
Okay, reading further I don't think you will be able to install it. 

I would recommend you to download the source code from [here 0.2.63](https://github.com/hey24sheep/azure-flutter-tasks/releases/tag/node6_0.2.63) and ctrl+f "hey24shee" with your company-id. Then run the build-with-publish script and then you can install/upload the vsix on publisher website.

**Comment by RivkaAltshuler** [comment]
Thank you! you helped me very much!

At last, I used the following solution:
1. Take the VSIX file, rename it to be a ZIP file, and edit the content using WinRAR
2. Changed the publisher in extension.vsixmanifest
3. Iterate the folders, for each task.json replace the id with a new generated GUID.
4. Navigate to the build definitions (TFS 2018) and export the problematic build definition (a JSON file is downloaded)
5. iterate again the folders, and replace the ids in the JSON file, each old id is replaced with the new id
6. Create a new build definition by importing the JSON file

**Comment by hey24sheep** [comment]
@RivkaAltshuler I am glad, you were able to rebuild vsix 👍🏼

**Comment by RivkaAltshuler** [comment]
I am not sure that I have the required developer tools, so I prefered the above solution

**Comment by hey24sheep** [comment]
Oh, I understand.
