### ISSUE TITLE
Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.

### ISSUE THREAD

**Issue by nanocortex** [hey24sheep/azure-flutter-tasks#29]
After upgrading gradle version to 7.3.3 I got following error while building:

```
[  +24 ms] Unzipping /Users/runner/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z/gradle-7.3.3-bin.zip to /Users/runner/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z
[+2012 ms] Set executable permissions for: /Users/runner/.gradle/wrapper/dists/gradle-7.3.3-bin/6a41zxkdtcxs8rphpq6y0069z/gradle-7.3.3/bin/gradle
[ +882 ms] Starting a Gradle Daemon (subsequent builds will be faster)
[+60816 ms] FAILURE: Build failed with an exception.
[        ] * Where:
[        ] Build file '/Users/runner/work/1/s/src/android/app/build.gradle' line: 24
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':app'.
[        ] > Failed to apply plugin 'com.android.internal.application'.
[        ]    > Android Gradle plugin requires Java 11 to run. You are currently using Java 1.8.
[        ]      You can try some of the following options:
[        ]        - changing the IDE settings.
[        ]        - changing the JAVA_HOME environment variable.
[        ]        - changing `org.gradle.java.home` in `gradle.properties`.
[        ] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[        ] > Run with --info or --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 1m 8s

```

![image](https://user-images.githubusercontent.com/40443396/149356070-1f10f55c-7022-4671-a426-5ba8d396cebb.png)

Should I perhaps install java before building flutter?

**Comment by nanocortex** [comment]
Yes it's building locally. I've already done all things provided in StackOverflow link.

Change which started build errors: 
![image](https://user-images.githubusercontent.com/40443396/149406429-905b24ef-c113-4118-88ff-725b50968cd0.png)

I suspect it's because of minimum JDK version required for gradle-plugin (JDK 11): https://developer.android.com/studio/releases/gradle-plugin.html#compatibility

**Comment by hey24sheep** [comment]
Hi, this issue has nothing to do with the extension. If you read the code of the "Tasks", you will see that it just downloads "Flutter SDK" and run bash commands on it.

Issue is related to Azure Agent Pool running your build. Azure-DevOps agents has pre-installed stuff on it which could/n't be latest. You have to check in your pool details, which version Microsoft is using.

Go to your "Project Settings -> Agent Pools (under pipelines heading) ", select your "Agent Pool" you are using in your Build Pipeline then go to "Details" tab. On this page you will see a lengthy list of all the stuff installed on it. Check, Java and Grade version in that. 

Here is what the details page looks like
![Capture](https://user-images.githubusercontent.com/31468022/149412149-e44b603c-a201-4a5e-ac1f-60663f96574a.PNG)

**Comment by hey24sheep** [comment]
Also, note that the image is of a "hosted agent". If you are running agents locally, you have to figure this out yourself. If your hosted agent shows old versions, that means, Microsoft hasen't updated it yet. You can open a new issue on Microsoft's DevOps [Github](https://github.com/microsoft/azure-pipelines-agent/issues) or you can try [this](https://stackoverflow.com/questions/61124946/how-to-you-use-a-specific-version-of-java-in-azure-devops-agent-without-download)

**Comment by nanocortex** [comment]
So it came down to installing java before building flutter. I've done steps provided in [your link](https://stackoverflow.com/questions/61124946/how-to-you-use-a-specific-version-of-java-in-azure-devops-agent-without-download) and now It works. Thanks a lot for your help. Awesome work with this plugin :)

**Comment by hey24sheep** [comment]
> So it came down to installing java before building flutter. I've done steps provided in [your link](https://stackoverflow.com/questions/61124946/how-to-you-use-a-specific-version-of-java-in-azure-devops-agent-without-download) and now It works. Thanks a lot for your help. Awesome work with this plugin :)

That is because you are using too "latest" of the tech. Microsoft, doesn't upgrade agent pools to latest stuff because it can impact other users who have "Production" envs running. As you know, many people don't upgrade production environments to latest unless after big meetings and fully testing the systems.

I am glad it is working for you now.

**Comment by michaelsoliman1** [comment]
Had the same issue, will share my solution if anyone needed it, 
The issue happened because as @hey24sheep said, the Java version installed were below 11, if you're using [macOS-latest](https://github.com/actions/runner-images/blob/main/images/macos/macos-11-Readme.md#java), the default version is 8, so i had to change it to [ubuntu-latest](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#java) that had the Java version defaults to 11
