### ISSUE TITLE
Flutter test output is not read by Azure Pipelines

### ISSUE THREAD

**Issue by jgoyvaerts** [hey24sheep/azure-flutter-tasks#30]
When running Flutter test, Azure pipelines can not recognize the current test output to show which tests failed in a structured and nice way.

However, there's a way to convert the current test output to XML (https://pub.dev/packages/junitreport) , and then run the Publish Test Results Task (https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results) to display them correctly.

It would be cool if this Task did both those things automatically (perhaps with a parameter to enable this behavior on flutter test), would make the integration with Azure a lot nicer!

**Comment by hey24sheep** [comment]
Hi @jgoyvaerts, all of this already happens in the "Test Task". You can check [this code line](https://github.com/hey24sheep/azure-flutter-tasks/blob/f6f3044433fd6989aba6c5e0e35222e7cc72180e/tasks/test/index.ts#L55).

**Comment by jgoyvaerts** [comment]
Cool, I missed that! Is there something I need to do to enable this? Since it doesn't seem to work out of the box on Azure Devops

**Comment by hey24sheep** [comment]
It works out of the box, this setting is enabled by default. 

Yes, there is a "Publish Test Results" checkbox on the setting page for "Test Task". 

Through Yaml setting it's key is [this](https://github.com/hey24sheep/azure-flutter-tasks/blob/f6f3044433fd6989aba6c5e0e35222e7cc72180e/tasks/test/task.json#L65) like so `publishTests: true`.

But, it should already be enabled for you. It is enabled by default. If you want to read your test reports, you can go to your "Pipeline -> Build -> Runs" or "Test Plans -> Runs"

**Comment by jgoyvaerts** [comment]
I found the problem, I was using Flutter Command task to run tests, instead of Flutter Test task. Thanks for the help pointing me in the right direction!

**Comment by hey24sheep** [comment]
👍🏻 glad, you found the problem.
