### ISSUE TITLE
ioS Build failed

### ISSUE THREAD

**Issue by Stewioie** [hey24sheep/azure-flutter-tasks#31]
Running "flutter pub get" in flutter_tools...                       5.4s
Running "flutter pub get" in s...                                2,918ms
Building xxxxxxxxxxxxx for device (ios-release)...

Automatically signing iOS for device deployment using specified development team in Xcode project: XXXXXXXX
Running Xcode build...                                          
Xcode build done.                                            6.5s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **

Xcode's output:
↳
    diff: /Podfile.lock: No such file or directory
    diff: /Manifest.lock: No such file or directory
    error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

Encountered error while building for device.

As I see the task (for iOS) skipped the pod install part.

need something more config or it's an issue?

Thanks

**Comment by hey24sheep** [comment]
Hi, pod install is skipped if it is already installed (as it gets auto installed on flutter install (If I remember correctly)). It has nothing to do with it.

Your error specifically shows the problem. In our pipelines, we do not do pod install or update. Though we definitely do "pod repo update"
```
diff: /Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```

You could check [this ](https://stackoverflow.com/questions/21366549/error-the-sandbox-is-not-in-sync-with-the-podfile-lock-after-installing-re#:~:text=You%20should%20be%20able%20to,folder%20in%20your%20project%20folder) and try the solutions here.

You could also try adding a new CMD Task "pod repo update" as command in 'your_flutter_project/ios'.

**Comment by hey24sheep** [comment]
I am closing this issue in response to commit 8a3d365. Feel free to create a new issue if you face any issues.
