### ISSUE TITLE
iOS build stuck

### ISSUE THREAD

**Issue by andiahmadfauzy** [hey24sheep/azure-flutter-tasks#34]
Hi, first of all thank you for this extension
I got an issue for building the ios version. It got stuck I don't know why

this is the piece of log from azure devops:
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
   100 20.7M  100 20.7M    0     0   101M      0 --:--:-- --:--:-- --:--:--  103M
                    Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220221-3605-1hsfyx2'...
                    Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220221-3605-10kzf5g'...
                    Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220221-3605-11jcx8l'...
                    Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220221-3605-15hxnhn'...
                    Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220221-3605-18ifajs'...
                    Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220221-3605-1xxpesk'...

               [!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `[https://guides.cocoapods.org/syntax/podfile.html#platform`.](https://guides.cocoapods.org/syntax/podfile.html#platform%60.)

               [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).

[  +26 ms] Fingerprint write error: FileSystemException: Cannot open file, path = 'build/ios/pod_inputs.fingerprint' (OS Error: No such file or directory, errno = 2)
[   +5 ms] executing: /usr/bin/plutil -convert xml1 -o - /Users/runner/work/1/s/ios/Runner/Info.plist
[  +13 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Users/runner/work/1/s/ios/Runner/Info.plist
[        ] <?xml version="1.0" encoding="UTF-8"?>
           <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "[http://www.apple.com/DTDs/PropertyList-1.0.dtd">](http://www.apple.com/DTDs/PropertyList-1.0.dtd%22%3E)
           <plist version="1.0">
           <dict>
           	<key>CFBundleDevelopmentRegion</key>
           	<string>$(DEVELOPMENT_LANGUAGE)</string>
           	<key>CFBundleExecutable</key>
           	<string>$(EXECUTABLE_NAME)</string>
           	<key>CFBundleIdentifier</key>
           	<string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
           	<key>CFBundleInfoDictionaryVersion</key>
           	<string>6.0</string>
           	<key>CFBundleName</key>
           	<string>Australian Ethical</string>
           	<key>CFBundlePackageType</key>
           	<string>APPL</string>
           	<key>CFBundleShortVersionString</key>
            <false/>
           	<key>kTCCServiceMediaLibrary</key>
           	<string>media</string>
           </dict>
           </plist>
[  +14 ms] Running Xcode build...
[   +1 ms] executing: [/Users/runner/work/1/s/ios/] xcrun xcodebuild -configuration Release VERBOSE_SCRIPT_LOGGING=YES -workspace Runner.xcworkspace -scheme Runner -sdk iphoneos -destination generic/platform=iOS -resultBundlePath /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/flutter_tools.vAO5bn/flutter_ios_build_temp_dirvtIxlF/temporary_xcresult_bundle -resultBundleVersion 3 FLUTTER_SUPPRESS_ANALYTICS=true COMPILER_INDEX_STORE_ENABLE=NO -archivePath /Users/runner/work/1/s/build/ios/archive/Runner archive

and because the actual log is really long and I can't copy and paste to this comment, here is the raw log: 
https://dev.azure.com/australianethicalmobileapp/d7356a76-73cc-465d-b8ec-becedadbb375/_apis/build/builds/388/logs/12

Thanks

**Comment by andiahmadfauzy** [comment]
oh my bad, here you go: 
[log-flutter-ios.txt](https://github.com/hey24sheep/azure-flutter-tasks/files/8113203/log-flutter-ios.txt)

I'm successfully installed via locally but the issue happens when using your extension in azure devops. Thanks

**Comment by hey24sheep** [comment]
If you read the file you will know the error is with your Coco Pod Install.

If you read this line : 2901
```log
[  +17 ms] Error output from CocoaPods:
2022-02-22T01:30:53.8507720Z            ↳
2022-02-22T01:30:53.8508710Z [        ]          Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220222-4677-1oaicze'...
2022-02-22T01:30:53.8509770Z                     Cloning into '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/d20220222-4677-hxhcxm'...
2022-02-22T01:30:53.8510310Z                     Updating files:  58% (2390/4089)
```

and this line (also, it shows you a hint what is wrong)
``` log
 [!] Automatically assigning platform `iOS` with version `12.0` on target `Runner` because no platform was specified. Please specify a platform for this target in your Podfile. See `https://guides.cocoapods.org/syntax/podfile.html#platform`.
2022-02-22T01:30:53.8600370Z 
2022-02-22T01:30:53.8602120Z                [!] CocoaPods did not set the base configuration of your project because your project already has a custom config set. In order for CocoaPods integration to work at all, please either set the base configurations of the target `Runner` to `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` or include the `Target Support Files/Pods-Runner/Pods-Runner.profile.xcconfig` in your build configuration (`Flutter/Debug.xcconfig`).
2022-02-22T01:30:53.8603090Z 
2022-02-22T01:30:53.8604270Z [  +30 ms] Fingerprint write error: FileSystemException: Cannot open file, path = 'build/ios/pod_inputs.fingerprint' (OS Error: No such file or directory, errno = 2)
2022-02-22T01:30:53.8605720Z [   +8 ms] executing: /usr/bin/plutil -convert xml1 -o - /Users/runner/work/1/s/ios/Runner/Info.plist
2022-02-22T01:30:53.8606780Z [  +15 ms] Exit code 0 from: /usr/bin/plutil -convert xml1 -o - /Users/runner/work/1/s/ios/Runner/Info.plist
```
If you read the log from line 2901 to 3125, you will see it is getting stuck in pod install of some repository. 

- I will recommend you to do pod install before as another step and then check if it is working. Check [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/package/cocoapods?view=azure-devops) extension. 
- Pod install as another step will split it into a sub task (reducing the chance of timeouts)
- Second, you can also increase your agent pipeline timeout. In our organization we have increased timeout limits because we have a lot of stuff building.

**Comment by hey24sheep** [comment]
I am closing this issue in response to commit 8a3d365. Feel free to create a new issue if you face any issues.
