### ISSUE TITLE
dart-define not working for building web target

### ISSUE THREAD

**Issue by haukepribnow** [hey24sheep/azure-flutter-tasks#38]
When specifying "dartDefine" or "dartDefineMulti" in a task to build a web target, this setting is ignored. Consequently, no "--dart-define" argument gets passed to the flutter tool.

Based on a quick look at the code, passing any of the two settings to the web target build seems to simply not be implemented yet.

Compare this line for the Android target that includes "dartDefine" variables:
https://github.com/hey24sheep/azure-flutter-tasks/blob/8a3d3658143dec7c26d48a1b05311ba6623d8709/tasks/build/index.js#L71

...with this line for the web target that does not:
https://github.com/hey24sheep/azure-flutter-tasks/blob/8a3d3658143dec7c26d48a1b05311ba6623d8709/tasks/build/index.js#L79

**Comment by hey24sheep** [comment]
Hi, I have fixed the code and added both the args to web and desktop builds. Updated extension will show up in few minutes.

I am closing this issue in response to latest commit [8f46389](https://github.com/hey24sheep/azure-flutter-tasks/commit/8f463890f1182e54aec9286fca0c321fb9d86b54). Feel free to re-open or create a new issue in case of a problem.
