### ISSUE TITLE
Can flutter be added to PATH?

### ISSUE THREAD

**Issue by IAmJulianAcosta** [hey24sheep/azure-flutter-tasks#39]
I'm using fastlane to build the application, but it looks like `flutter` command doesn't get added to PATH, so the configuration that I have for fastlane breaks when trying to run a flutter command.

I would like to know if `flutter` can be called directly instead of using `- task: FlutterCommand` as I don't have that option from `fastlane`

**Comment by IAmJulianAcosta** [comment]
As a workaround: 
`- script: export PATH=$PATH:$(FlutterToolPath) && bundle exec fastlane ...` did the trick, leaving it for reference to other people with the same question

**Comment by hey24sheep** [comment]
@IAmJulianAcosta Hi, it does create an env variable "$(FlutterToolPath)" which is a path to Flutter sdk. So you can use Flutter commands as "$(FlutterToolPath)/flutter packages get" (as shown in Readme). 

I do not think there is another way of adding Flutter directly as an ENV Var. But, I will keep this issue open for a little bit and also add your workaround to the Readme with a reference to this issue for future ref.

**Comment by hey24sheep** [comment]
Added to [wiki](https://github.com/hey24sheep/azure-flutter-tasks/wiki/FAQs) and closing this as beyond scope.
