### ISSUE TITLE
Code signing method 

### ISSUE THREAD

**Issue by Talgat777** [hey24sheep/azure-flutter-tasks#5]
Hi!

I have a question regarding changing the code signing method for IOS. How can I specify these arguments:

--CODE_SIGN_STYLE="Manual" --CODE_SIGN_IDENTITY ="$(APPLE_CERTIFICATE_SIGNING_IDENTITY)" --PROVISIONING_PROFILE ="$(APPLE_PROV_PROFILE_UUID)"

I've tried specifying it as "Extra command arguments" in Flutter Build but got his error: Could not find an option named "CODE_SIGN_STYLE".

Thanks,
Talgat

**Comment by Talgat777** [comment]
Never mind, I disabled signing in Flutter Build and added Xcode Archive task where I can specify arguments. Closing the issue!

**Comment by hey24sheep** [comment]
Hi @Talgat777,

You are trying to sign your build archive. Flutter doesn't give you the ability to do so, read [here](https://flutter.dev/docs/deployment/ios#create-a-build-archive). IOS signing is done by the user separately. 

You will need 
- '[Apple Certificate Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-certificate?view=azure-devops)' to install the cert in your Azure Secure Files
- '[Apple Provisional Profile Task](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/install-apple-provisioning-profile?view=azure-devops)'
- Now you build using `Flutter Build Task` (you could also use Xcode Build Task), here do not select `Code sign application bundle checkbox`
- Generate Archive using Command task (if not using XCode build) `xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner archive -sdk iphoneos -configuration Release-production -archivePath Runner CODE_SIGN_STYLE=Manual CODE_SIGN_IDENTITY="your_identity"`
- Generate IPA using Command Task `xcodebuild -exportArchive -archivePath Runner.xcarchive -exportPath Runner -exportOptionsPlist ios/export_prod_or_your_env_file.plist`
- '[Apple store connect](https://marketplace.visualstudio.com/items?itemName=ms-vsclient.app-store' to publish/release your app

**Comment by hey24sheep** [comment]
I am glad you found a solution. I have also added my solution if it helps you.
