### ISSUE TITLE
Wrong value for a cache path

### ISSUE THREAD

**Issue by sj-asm** [hey24sheep/azure-flutter-tasks#51]
The `FlutterEnv` task sets, among other things, the variable `FlutterCachePath` to [.pub-cache/bin](https://github.com/hey24sheep/azure-flutter-tasks/blob/d748ae92f6339a944c6c51fd62a9d4fcbe85b16d/tasks/env/index.js#L17), while `flutter` uses `.pub-cache` for caching.

Output example for `flutter pub get -v`:

```text
[   +4 ms] Using /Users/runner/hostedtoolcache/Flutter/3.0.5/macos/flutter/.pub-cache for the pub cache.
```

**Comment by hey24sheep** [comment]
I have updated the extension with the necessary change. Update should be available in about 20 minutes on the marketplace. If you have any further issues or suggestions, feel free to create a new issue or re-open this one (if not fixed).
