### ISSUE TITLE
flutter build APK failed

### ISSUE THREAD

**Issue by AhmedKhattab95** [hey24sheep/azure-flutter-tasks#57]
when running build APK it fails even it generate apk successfully local
attached log file for task
[log.docx](https://github.com/hey24sheep/azure-flutter-tasks/files/9922175/log.docx)

**Comment by hey24sheep** [comment]
Hi, can you please print the log here in a comment instead of attaching files. You do not need to print the whole log, just print the failing part of it.

**Comment by hey24sheep** [comment]
@AhmedKhattab95 if your build is working now, please close this issue. Otherwise please print the error part of the log here.
