### ISSUE TITLE
Gradle build failed

### ISSUE THREAD

**Issue by omarhaj007** [hey24sheep/azure-flutter-tasks#60]
Gradle build failed to produce an .apk file. It's likely that this file was generated under C:\agent\_work\3\s\mobile\build, but the tool couldn't find it.
##[error]Error: The process 'C:\agent\_work\_tool\Flutter\3.3.8\windows\flutter\bin\flutter.bat' failed with exit code 1

My Code : 
    - task: FlutterBuild@0
      inputs:
        target: 'apk'
        projectDirectory: 'mobile'
        buildNumber: '$(Build.BuildNumber)'
        buildName: '$(versionName)'
        entryPoint: 'lib/main-development.dart'

**Comment by hey24sheep** [comment]
Hi, sorry for the delay. Did you solve it?

**Comment by hey24sheep** [comment]
I am assuming this to be fixed, if it's not feel free to reopen and provide further information.
