### ISSUE TITLE
Cache of Flutter Install is not working?

### ISSUE THREAD

**Issue by BenjaminZaiser** [hey24sheep/azure-flutter-tasks#61]
Hi,

Thanks for your pretty cool extension. It is working fine so far, but I found the following behavior which is not working as expected for me:

My pipeline:
```
  - task: FlutterInstall@0
    inputs:
      mode: 'auto'
      channel: 'stable'
      version: 'latest'
```

The log shows:
```
Starting: FlutterInstall
==============================================================================
Task         : Flutter Install Task
Description  : Install the Flutter environment.
Version      : 0.3.5
Author       : Hey24sheep
Help         : For more information, take a look at the Flutter [documentation](https://flutter.io/)
==============================================================================
Downloading: https://storage.googleapis.com/flutter_infra_release/releases/stable/macos/flutter_macos_3.3.10-stable.zip
Extracting archive
/usr/bin/unzip /Users/runner/work/_temp/123
Archive:  /Users/runner/work/_temp/123
   creating: flutter/
  inflating: flutter/CODE_OF_CONDUCT.md

...

Caching tool: Flutter 3.3.10 macos
Found tool in cache: Flutter 3.3.10 macos
Finishing: FlutterInstall
```
Which takes up about 1min (!)

If the cache would work correctly, I would assume that the next time I execute the pipeline including Flutter Install, it won't download the ZIP file from Google again. Instead I would expect a restore from the Azure Pipeline Cache. Which should be much faster and cause no network traffic for Google.

Please can you have a look?

Thanks
Ben

**Comment by hey24sheep** [comment]
Hi, thank you for your kind words.

I think this issue is related to #2 It's a problem from a Microsoft's end. It gets fixed and unfixed by itself. 

Read the #2 issue in closed issues. You can use my other extension to create your own caching for Flutter that way it will be fixed forever. 

From code point the caching is already implemented and nothing is changed from API standpoint.

**Comment by hey24sheep** [comment]
Closing this issue as it seems to be caching on latest. You can create a bug report on "https://github.com/microsoft/azure-pipelines-agent".
