### ISSUE TITLE
SDK License Issue

### ISSUE THREAD

**Issue by acidaes** [hey24sheep/azure-flutter-tasks#62]
[!] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
 ! Some Android licenses not accepted.  To resolve this, run: flutter doctor --android-licenses

How to resolve this on Azure DevOps Pipeline.
As when we run this command doctor --android-licenses
 through flutter command task its asking permission.

Kindly help.

**Comment by hey24sheep** [comment]
Run this locally

(your android_sdk folder exact path)\tools\bin\sdkmanager --licenses

Also license issue is not on Azure. Just accept licenses locally and push normal. It should run. 

PS- you can't run doctor on Azure. It won't make sense.

**Comment by acidaes** [comment]
Thanks Narayan,
 It worked.
