### ISSUE TITLE
Run Dart Commands

### ISSUE THREAD

**Issue by MelbourneDeveloper** [hey24sheep/azure-flutter-tasks#63]
It would be very nice to run Dart commands instead of Flutter commands. The Flutter analyzer, for example, works differently from the Dart analyzer. The --no-fatal-warnings doesn't work with the flutter command. The command will return an error code if you run the analyzer and have warnings. If you run the same with Dart, it works fine.

`dart analyze lib --no-fatal-warnings`

You can easily try it out yourself. Write some Dart code that produces a warning (orange) in vscode. Run both tools. Flutter will return an error code, but Dart won't. This breaks the DevOps pipelines for us because we can't run the Dart command line

**Comment by hey24sheep** [comment]
Hi, that's a nice feature to add on but the functionality still exists.

What I mean by that is, you can run "Flutter Install" then you have 3 environment variables which you can use in a "CMD Task" or "Powershell Task".

Read the docs, variable name is available there with how to use it. All you have to do is, just add a new command or Powershell script task. 

I hope that solves your issue.

**Comment by MelbourneDeveloper** [comment]
Thankyou
