### ISSUE TITLE
ITMS-90426: Invalid Swift Support 

### ISSUE THREAD

**Issue by ElaineBSchwaner** [hey24sheep/azure-flutter-tasks#65]
Thanks for this plugin.

I am finally on the last step, that is deploying on App Store.
Building the ipa and deploying to Firebase App Distribution worked without a problem.

But I am trying to deploy it on App Store and I received an e-mail saying:

Dear Developer,
We identified one or more issues with a recent delivery for your app, "XXX" 2.0.0 (16). Please correct the following issues, then upload again. 
**ITMS-90426: Invalid Swift Support** - The SwiftSupport folder is missing. Rebuild your app using the current public (GM) version of Xcode and resubmit it. 

My pipeline:

          - task: FlutterInstall@0
            displayName: Installing Flutter SDK
            inputs:
              mode: 'auto'
              channel: 'stable'
              version: 'custom'
              customVersion: '3.0.5'

          - task: FlutterBuild@0
            displayName: Building iOS
            inputs:
              target: 'ios'
              iosCodesign: false
              projectDirectory: '$(root)'
              buildFlavour: $(buildConfiguration)
              entryPoint: 'lib/run/main_$(buildConfiguration).dart'

          - task: Xcode@5
            inputs:
              actions: 'archive'
              configuration: 'Release-$(buildConfiguration)'
              sdk: 'iphoneos'
              xcWorkspacePath: 'ios/Runner.xcworkspace'
              scheme: $(buildConfiguration)
              packageApp: true
              archivePath: '$(buildDirectoryiOS)'
              exportPath: '$(buildDirectoryiOS)'
              signingOption: 'manual'
              signingIdentity: '$(APPLE_CERTIFICATE_SIGNING_IDENTITY)'
              provisioningProfileUuid: '$(APPLE_PROV_PROFILE_UUID)'
              args: '-verbose'
              useXcpretty: false

          - task: AppStoreRelease@1
            inputs:
              serviceEndpoint: 'App Store Service'
              releaseTrack: 'Production'
              appIdentifier: 'com.xxx'
              appType: 'iOS'
              ipaPath: '$(buildDirectoryiOS)/*.ipa'
              shouldSkipWaitingForProcessing: true

Can you help me?

**Comment by hey24sheep** [comment]
Hi and thank you. I have personally never seen this error ever.

I would recommend you ask this on Flutter repo as the issue seems to be related to either Flutter SDK or XCode and not with this extension. Maybe someone from Flutter team can help.

**Comment by hey24sheep** [comment]
Hi, is this issue fixed. It will get closed soon as stale-inactive.

**Comment by hey24sheep** [comment]
Closing as stale, inactive and assumed solved.

Follow this to solve your issue.
- [Stackoverflow](https://stackoverflow.com/questions/32559204/invalid-swift-support-the-swiftsupport-folder-is-empty)
