### ISSUE TITLE
ios ipa build fails ExportOptions

### ISSUE THREAD

**Issue by martipello** [hey24sheep/azure-flutter-tasks#7]
i have this build task in my pipelines yaml file,

    - task: FlutterBuild@0
      inputs:
        target: 'ipa'
        projectDirectory: '$(System.DefaultWorkingDirectory)/apps/wordskii2/'
        flutterDirectory: './flutter'
        buildFlavour: 'prod'
        buildName: '1'
        iosCodesign: true
        entryPoint: 'lib/main_prod.dart'
        dartDefine: 'TIMESHEET_BOX_KEY=$(timesheet_database_key) --dart-define FILE_BOX_KEY=$(timesheet_database_key)'
        extraArgs: '--export-options-plist=ios/ExportOptions.Prod.plist --release'

and it fails with this error: 

"ios/ExportOptions.Prod.plist --release" property list does not exist.

the logs say the command that was executed was this : 

/Users/runner/hostedtoolcache/Flutter/2.5.0-stable/macos/flutter/bin/flutter build ipa --build-name=1 --build-number=20210909.5 --target=lib/main_prod.dart --flavor=prod --dart-define=TIMESHEET_BOX_KEY=*** --dart-define FILE_BOX_KEY=*** --export-options-plist=ios/ExportOptions.Prod.plist --release

which looks correct to me 🤷
it seems the command thinks that --release is part of the file name for export options

This is running on a big sur macOS also i can copy and paste this command into my terminal and run it and it runs successfully

**Comment by martipello** [comment]
just noticed there is an argument for export options will try that first

**Comment by martipello** [comment]
yup fixed it thank you

**Comment by hey24sheep** [comment]
Glad it is fixed 👍🏻
