### ISSUE TITLE
dart not in the PATH 

### ISSUE THREAD

**Issue by vipw** [hey24sheep/azure-flutter-tasks#73]
I'm using melos and the FlutterCommand to bootstap is failing because dart is not in the PATH.

```
Starting: Bootstrap monorepo
==============================================================================
Task         : Flutter Command Task
Description  : Launch a custom Flutter command with custom arguments.
Version      : 0.3.0
Author       : Hey24sheep
Help         : Don't forget to insert a 'Flutter Install' task before. [More Information](https://github.com/hey24sheep/azure-flutter-tasks)
==============================================================================
C:\Windows\system32\cmd.exe /D /S /C "C:\hostedtoolcache\windows\Flutter\3.7.11\windows\flutter\bin\flutter.bat pub global run melos bootstrap"
'dart' is not recognized as an internal or external command,
operable program or batch file.
pub finished with exit code 1
##[error]Error: The process 'C:\hostedtoolcache\windows\Flutter\3.7.11\windows\flutter\bin\flutter.bat' failed with exit code 1
Finishing: Bootstrap monorepo
```

I think this can be fixed fairly easily by appending FLUTTER_TOOL_PATH_ENV_VAR to the process.env[PATH] before executing the task.

**Comment by hey24sheep** [comment]
I do not understand what you wish to do. Flutter command is a task to run Flutter commands only as the command path is flutter bin and not dart bin. 

- $(FlutterToolPath) - can be used as "$(FlutterToolPath)/flutter packages get"
- $(FlutterPubCachePath) can be used as "$(FlutterPubCachePath)/pubver set $(Version)"
- $(DartToolPath) - can be used as "$(DartToolPath)/dart prog.dart arg1"

These env vars are already there. You could run them as you wish in a "CMD Task" to run your melos.

**Comment by hey24sheep** [comment]
Your error I think is from melos. As it's internal variable is "dart". You could remap the environment variables and try that.

**Comment by ewertonls** [comment]
@hey24sheep some flutter or dart tools, such as [`melos`](https://pub.dev/packages/melos) need to find `dart` or `flutter` on `PATH`, otherwise it'll fail to execute.

The `task.prependPath` can be used prepend the `DartToolPath` and/or `FlutterToolPath` to the system `PATH` environment variable.

https://github.com/microsoft/azure-pipelines-task-lib/blob/4086d6bef172fe1329d3006ccacc324e05baac1e/node/task.ts#L2108-L2111

```ts
export function prependPath(path: string) {
    assertAgent("2.115.0");
    command("task.prependpath", null, path);
}
```

Like so on https://github.com/hey24sheep/azure-flutter-tasks/blob/master/tasks/env/index.ts:
```ts
	// 2.2 Create dart environment variable
	let fullDartPath: string = path.join(fullFlutterPath, DART_EXE_RELATIVEPATH);
	task.debug(`Set ${DART_TOOL_PATH_ENV_VAR} with '${fullDartPath}'`);
	task.setVariable(DART_TOOL_PATH_ENV_VAR, fullDartPath);

	task.setResult(task.TaskResult.Succeeded, "Environment Variables Set");

        // 2.3 Prepend to PATH environment variable
        task.prependPath(fullFlutterPath);
        task.prependPath(fullDartPath);
}
```

**Comment by hey24sheep** [comment]
Thanks, I didn't know something like this is there. I will try to add it this weekend.

**Comment by DanielRossini1** [comment]
i'm having the same problem, @hey24sheep some updates about?

**Comment by hey24sheep** [comment]
@DanielRossini1 I am a little busy with work. I will try my best to implement it this week and publish the extension

**Comment by Zazo032** [comment]
Hey @hey24sheep, just as an extra follow-up, the FlutterAnalyze no longer works with the latest due to a similar issue:
```
The "format" command is deprecated. Please use the "dart format" sub-command instead, which has the same command-line usage as "flutter format".
```

**Comment by hey24sheep** [comment]
> Hey @hey24sheep, just as an extra follow-up, the FlutterAnalyze no longer works with the latest due to a similar issue:
> 
> ```
> The "format" command is deprecated. Please use the "dart format" sub-command instead, which has the same command-line usage as "flutter format".
> ```

This is different. You can use a "cmd" task to run `$(DartToolPath)/dart format` and it will work. The above issue is different.

**Comment by hey24sheep** [comment]
Hi everyone, I have updated the extension as per the given solution by @ewertonls (thank you for your kind help). Feel free to reopen in case of any issue regarding the same, thank you.
