### ISSUE TITLE
Flutter install failed in ubuntu

### ISSUE THREAD

**Issue by courfeyrak** [hey24sheep/azure-flutter-tasks#75]
Hi, hope you can help me.

When running the flutter install task I got the following error: 

##[error]TypeError: Cannot read property 'hash' of undefined

Thanks

**Comment by hey24sheep** [comment]
Provide the log of what the error is, what is your input config. I can't help you without any information

**Comment by harshhhh15** [comment]
The error message you provided is not very specific, but it sounds like it could be related to a problem with the Flutter installation process. Here are some steps you can try to resolve the issue:

1. Check that you have the latest version of Flutter installed. You can run `flutter upgrade` to make sure you have the latest version.

2. Check that your system meets the minimum requirements for running Flutter. You can find the requirements on the Flutter website.

3. If you recently updated Flutter, try running `flutter clean` to clean the build artifacts and then running `flutter pub get` to get the latest packages.

4. If the error persists, try uninstalling and reinstalling Flutter.

5. If none of the above steps work, try creating a new Flutter project and see if the error still occurs. If the error occurs in a new project, it could be a problem with your system or installation. If the error does not occur in a new project, it could be a problem with your project code.

If you are still having trouble after trying these steps, you may need to provide more information about your environment, Flutter version, and the specific command you are running.

**Comment by hey24sheep** [comment]
Hi, is this issue fixed. It will get closed soon as stale-inactive.
