### ISSUE TITLE
Task does not get correct version of package during the build. 

### ISSUE THREAD

**Issue by ugurcan** [hey24sheep/azure-flutter-tasks#76]
Hello, 

I am running the build task on Azure Devops.

My dependency is "connectivity_plus: ^3.0.2"  on pubspec.yaml file. But during the build apk, it is getting "connectivity_plus 3.0.6" which is latest version. 

My previous pubspec.yaml file was containing to "connectivity_plus 3.0.6" version but i've downgraded to "connectivity_plus 3.0.2" again. But it is still getting something from the cache like or somewhere else and trying to install latest version of it. My logs are

Got dependencies in ../../../../../../opt/hostedtoolcache/Flutter/3.7.12/linux/flutter/packages/flutter_tools!
Running "flutter pub get" in mobile...
Resolving dependencies...
+ archive 3.3.7
+ args 2.4.1
+ async 2.10.0 (2.11.0 available)
+ aws_common 0.1.1 (0.4.2+5 available)
+ aws_signature_v4 0.1.2 (0.3.1+7 available)
+ boolean_selector 2.1.1
+ characters 1.2.1 (1.3.0 available)
+ clock 1.1.1
+ collection 1.17.0 (1.17.1 available)
+ connectivity_plus 3.0.6

Is there some way to override this, i want to use my current pubspec.yaml file with exact versions with packages.

**Comment by ugurcan** [comment]
This is the my yaml file.

dependencies:
  flutter:
    sdk: flutter
  platform: ^3.1.0
  lottie: ^1.4.3
  provider: ^6.0.3
  shared_preferences: ^2.0.18
  http: ^0.13.5
  connectivity_plus: ^3.0.2

**Comment by hey24sheep** [comment]
Hi, remove '^' this symbol from the packages you don't want to upgrade. This symbol is a universal identifier for all package managers stating the package should be upgraded to latest. 

You can Google the package symbols for better understanding. 

I hope this fixed your issue, close this issue once verified and fixed.

**Comment by ugurcan** [comment]
Thank you, I didn't know that or I forgot. But anyway build done and bug is gone :)
