### ISSUE TITLE
Build IPA fails with newer crashlytics version.

### ISSUE THREAD

**Issue by TDuffinNTU** [hey24sheep/azure-flutter-tasks#78]
https://github.com/firebase/flutterfire/issues/10994 documents this in more detail, but for reproduction:

```
Install Firebase Crashlytics 3.3.0 with sdk: ">=2.18.0 <3.0.0"

run command flutter build ipa --flavor production -t lib/main_production.dart --obfuscate --split-debug-info=debug
Get the below error

error: Flutter build with --obfuscate enabled. Crashlytics does not support uploading obfuscated dSYMs via the command
line. Please upload dSYMs through the Firebase console web uploader at
https://firebase.corp.google.com/project/_/crashlytics
```

It appears that the IPA build task is now failing due to the `--obfuscate` flag despite this working in older versions.

**Comment by hey24sheep** [comment]
This issue isn't related to this extension but with Firebase. Build task doesn't add `--obfuscate` unless a user pass it through `extraArgs` or it's run with a custom command through `command task`

I can't help you much here as I have no control over how other related libraries change and how users use other packages. My extension is just to build Flutter app using Azure Pipelines.

You can either
- Downgrade your Flutter version in the `install task` as the issue you attached says
or
- Do as the error log suggests, "Upload the dSYMs through the Firebase console"

If above options doesn't work for you then it will be better if you bump the same issue/thread (that you attached).

```
Error: Flutter build with --obfuscate enabled. Crashlytics does not support uploading obfuscated dSYMs via the command
line. Please upload dSYMs through the Firebase console web uploader at
https://firebase.corp.google.com/project/_/crashlytics
```
