### ISSUE TITLE
How do i build for different platform ?

### ISSUE THREAD

**Issue by Milos5611** [hey24sheep/azure-flutter-tasks#8]
How to make `flutter build apk --split-per-abi` in the build? 
The only thing i see is that i put arn or arm64, but not both?

**Comment by hey24sheep** [comment]
Fixed in response to 999103b. Close this issue if this solves it. Thanks.

**Comment by Milos5611** [comment]
Let me test that quickly

**Comment by hey24sheep** [comment]
Assuming fixed, closing this issue in respect to latest fix 999103b. If you still have any issues, feel free to create a new issue instead.
