### ISSUE TITLE
iOS Build

### ISSUE THREAD

**Issue by coleary01** [hey24sheep/azure-flutter-tasks#80]
Does anyone have any more info on which Certs and Profiles to export and Xcode settings?

I am attempting to create the IPA so that can be published to the App Store.

I've tried exporting them from my machine and creating new ones on the portal.

No matter how many times I try (on my 39th revision!!), I constantly get:

```
/Users/runner/work/1/mobile_ui/ios/Runner.xcodeproj: error: No profiles for '{appName}' were found: 
Xcode couldn't find any iOS App Development provisioning profiles matching '{appName}'. 
Automatic signing is disabled and unable to generate a profile. 
To enable automatic signing, pass -allowProvisioningUpdates to xcodebuild. (in target 'Runner' from project 'Runner')
```

Android is working fine! :)

**Comment by hey24sheep** [comment]
Hi, it's your configuration issue. Only Google + StackOverflow can you help you with the setup. 

Read these attached links, [all related issues](https://github.com/hey24sheep/azure-flutter-tasks/issues?q=is%3Aissue+is%3Aclosed+ios+profile+), [issue#37](https://github.com/hey24sheep/azure-flutter-tasks/issues/37), [setup wiki](https://github.com/hey24sheep/azure-flutter-tasks/wiki/IOS-&-Android-Example-Setup-Guide) and [issue#49](https://github.com/hey24sheep/azure-flutter-tasks/issues/49) for same issue and fixed solutions. I hope it helps.
