### ISSUE TITLE
Consider renaming FlutterAnalyzeTask to FlutterAnalyze

### ISSUE THREAD

**Issue by ManuelRauber** [hey24sheep/azure-flutter-tasks#81]
Consider renaming FlutterAnalyzeTask to FlutterAnalyze so it fits the naming scheme of all other tasks in this package.

**Comment by hey24sheep** [comment]
Hi, I feel this could be done but I have my doubts. I do not want to break builds just for the namesake. 

Will the upgrade auto rename everyone's YAML file? If not, I apologize but I can't upgrade it as I do not want numerous builds to fail.

**Comment by ManuelRauber** [comment]
> Hi, I feel this could be done but I have my doubts. I do not want to break builds just for the namesake.
> 
> Will the upgrade auto rename everyone's YAML file? If not, I apologize but I can't upgrade it as I do not want numerous builds to fail.

Not sure about the auto rename, I don't think so.

Would it be possible to create a new task with the correct name and deprecate the old one?
So no existing build will break.

**Comment by hey24sheep** [comment]
That's what I thought so, it will break thousands of builds if I push this change.

To answer the other question: No, duplicates are not allowed directly but hacky implementation is there which I won't go for. A major issue with duplicate task is that a task is associated with a GUID and assets. You can't duplicate that GUID, and associating a new GUID to the same task is not the right approach as it makes duplicate references. 

I understand from the convention & OCD standpoint that it's a triggering. I overlooked the naming. I apologize but I don't think this change will be feasible but I really appreciate your thought and effort. Closing this issue as not feasible.
