### ISSUE TITLE
Unable to create build with flavor for iOS simulator

### ISSUE THREAD

**Issue by SBerenda** [hey24sheep/azure-flutter-tasks#86]
It is not possible to pass flavor name for iOS simulator build. 
See lines [249-251 of file tasks/build/index.js](https://github.com/hey24sheep/azure-flutter-tasks/blob/master/tasks/build/index.js#L251).
Flavour arg is pushed only for !simulator condition.

**Comment by hey24sheep** [comment]
Hi, 
You are the first person to ever open an issue for Simulator 😄 
There were multiple reasons of it not being there, First being the original author made it that way in 2020 and simulators aren't used heavily on Azure Pipelines and nor they can generate '.ipa' (at least to my knowledge). Also, is `flavor` even supported on simulator? 

**Solution**
You can pass the `--flavor your_flavor` or try `--flavor=your_flavor` to the `extraArgs` and by pass this restriction easily. You can refer to readme.

I added `extraArgs` just for these edge cases and if Flutter team adds any new functionality. 

Try `extraArgs` if in case for some reason it doesn't work. Feel free to re-open this issue.

**Comment by guulp** [comment]
I just came across this bug. The simulator build should not prevent setting a flavor. You may want to produce a simulator build in your pipeline as an artifact for QA to test with. You could have several flavors you are interested in testing with a simulator.
