### ISSUE TITLE
Command Failed

### ISSUE THREAD

**Issue by bobwiller** [hey24sheep/azure-flutter-tasks#9]
Thanks for creating/maintaining these tasks.  Quick question.  I need to run "pub run intl_utils:generate" before my build.  I have inserted a command, so my pipeline looks like this:

![pipeline](https://user-images.githubusercontent.com/2389999/133823137-9940cfc1-efed-492d-8372-5e0b8e7e2418.png)

When I run this, the flutterInstall task runs, but I get the following error on FlutterCommand:
"##[error]Error: The process '/opt/hostedtoolcache/Flutter/2.5.0-stable/linux/flutter/bin/flutter' failed with exit code 65"

Am I missing a step or something else?
Thanks for any help
Bob

**Comment by bobwiller** [comment]
sorry, didn't mean to close this - first day w/github :(

**Comment by hey24sheep** [comment]
Without any specific error it is hard to know what is going on.

Two things you could try
- Could you try running the same command on your local computer 
- Could you run the same command using "CMD task" on Azure use the command `$(FlutterToolPath) pub run intl_utils:generate`

**Comment by bobwiller** [comment]
Thx @hey24sheep  - got this working - I was missing a Command before this I needed to run `flutter pub get`.
