### ISSUE TITLE
Caching Flutter install for Parallel Builds (install as Artifact) 

### ISSUE THREAD

**Issue by Zazo032** [hey24sheep/azure-flutter-tasks#95]
We would like to run multiple jobs in parallel, so we have a common job that runs FlutterInstall, and other jobs that depend on the common one. The other jobs can't find `flutter` in the path. How could we cache the flutter installation to read it (not download) in the parallel jobs? If we have 6 parallel jobs, we would like to avoid running FlutterInstall 6 times to save some time.

**Comment by hey24sheep** [comment]
Hi,
Caching already implemented in this extension check this (line)[https://github.com/hey24sheep/azure-flutter-tasks/blob/0806b7e4dacc41b30924c0002a87e50c2ee90cad/tasks/install/index.ts#L42]. 

Caching is done for subsequent builds. Parallel builds are a different thing. If your parallel builds will include this "Install task", they will automatically become cached the 2nd time they run.

But, what I am getting is you want a single time run and cache for all. That is not caching but artifact. The way it will work is, you will need to upload the Flutter SDK as an artifact and then get that artifact during pipeline build and create the variables for build, etc.

Install doesn't have anything of the sort as I am not aware of how Artifacts work as I have not used them personally.
